### ISSUE TITLE
Looks good. An example would be nice

### ISSUE THREAD

**Issue by basarat** [fuselabs/jsxtyper#1]
After :

> JSXTyper generates TypeScript interfaces from your .jsx files. By referencing the generated .ts file and using the generated props and state interfaces you can make sure all data expected by the .jsx is supplied, and catch any typos at build-time.

Perhaps something along the lines of :

---

Given jsx:

``` js
// put sample jsx here
```

Generates a ts file:

``` ts
// put sample generated ts here
```

That can be used in your code as:

``` ts
// put ts code that user would type here
```

---

Thanks :rose: :+1:

**Comment by Rajeev-K** [comment]
Sample jsx and corresponding ts has been added to the README. Also, a complete sample project has also been added in the `SampleProject` folder.

**Comment by basarat** [comment]
awesome
